### ISSUE TITLE
snel v1.0.0 roadmap

### ISSUE THREAD

**Issue by buttercubz** [crewdevio/Snel#14]
## planned features and refactors:

- [x] create an build SPA projects
- [x] sass and less support
- [x] import maps support
- [ ] typescript support
- [ ] SSG and SSR support
- [ ] postcss support
- [ ] netlify, vercel, heroku etc. support
- [ ] deno deploy support
- [ ] binary self contained support for SSG and SSR mode

> if you want add others stuff in snel you can reply this issue

**Comment by Valexr** [comment]
Svelte code-slitting with Esbuild have a one trouble – have splitting js/css bundles, but can't load hash-bundle.css on client...

**Comment by Peyman-Borhani** [comment]
Consider compatibility with svelte-kit, whenever possible if it makes sense... 

Some random thoughts on this matter:

- makes it easier to use or migrate projects both ways. 
- it might reduce unseen future conflicts/issues.
- use same/similar syntax  and structure when possible. (commands/configs, etc...)
- a deno adapter where deno is runtime or helps svelte-kit and snel work together.
- or an adapter/compiler that compiles svelte-kit output to a snel/deno build.

**Comment by aadamsx** [comment]
Is there a timeframe around this roadmap?

**Comment by buttercubz** [comment]
> Is there a timeframe around this roadmap?

Unfortunately I do not have exact dates for these features since I work in open source in my spare time but any help or contribution will be well received.
